### PR TITLE
Deprecate this codebase in favor of the fieri included within Supermarket itself.

### PR DESCRIPTION
**Pull request by robbkidd**

### CODE REVIEW

**Comment by robbkidd** [comment]
@nellshamrell @tas50 :eyes:

**Comment by tas50** [comment]
🚢

**Comment by loganmeetsworld** [comment]
👍 on the language in the Readme and deprecation of Fieri. Not sure if we'd like Travis to be happy. If not, this looks good. If so, 👍 upon making Travis happy.

**Comment by nellshamrell** [comment]
I'm not worried about tests failing when deprecating a repo completely.
:shipit:

**Comment by robbkidd** [comment]
So we don't need to have a test for "this repo is empty." ✅

**Pull request merged**
